version: '3.8'

networks:
  timesheet:
    name: timesheet

services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql-timesheet-1
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE : timesheetdb
      MYSQL_USER : user
      MYSQL_PASSWORD : password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - timesheet

  redis:
    image: redis:latest
    container_name: redis-timesheet
    ports:
      - "6379:6379"
    networks:
      - timesheet
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:

  